pull_request_rules:
  - name: Automatic merge when CI passes and reviews approve
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=CI # replace "CI" with the name of your CI status check
    actions:
      merge:
        method: merge
  - name: Ask to resolve conflict
    conditions:
      - conflict
    actions:
      comment:
        message: This pull request is now in conflicts. Could you fix this @{{author}} ?
  - name: comment when a pull request is merged
    conditions:
      - merged
    actions:
      comment:
        message: Thank you for your contribution @{{author}}! Your pull request has been merged.
  - name: comment when a pull request is labeled "needs review"
    conditions:
      - label=needs review
    actions:
      comment:
        message: Thank you for your contribution! A reviewer will be assigned soon.
